version: "3"


services:
  my_app:
    image: ${REGISTRY}/${MY_APP_NAME}:${MY_APP_TAG}
    entrypoint:
      - java
      - -jar
      - /app/my_app.jar
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.port=${JMX_PORT}
      - -Dcom.sun.management.jmxremote.local.only=false
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.ssl=false
    env_file:
      - .my_app_env
    ports:
      - "${APP_PORT}:${APP_PORT}"

